### PR TITLE
Making GenerateKeys and PeekRowKey virtual

### PR DESCRIPTION
**Pull request by defr0zen**
Thanks for the implementation. I'd need to customize the keys for the table entities. For example, user key should be user.Id instead of user.Username and so on.
Making GenerateKeys and PeekRowKey virtual ideally solves my problem.

### CODE REVIEW

**Comment by dlmelendez** [comment]
@defrosted I am taking a look at these changes. They have the potential to break or have a severe performance impact a few operations on the user queries. The username was used as one of the keys to avoid a secondary query for username lookup. If you don't add an index for username for the UserStore.FindByNameAsync operation it will be incredibly slow once you get >100 users. This was an intentional trade off for performance to not have an arbitrary user id key to minimize the query operations on username lookup as described in the [Performance section.](https://dlmelendez.github.io/identityazuretable/#/techoverview)

**Comment by defrosted** [comment]
True, then I think the use case becomes quite specific to my needs so probably it should not be generalized. In my case usernames are not unique (only email is) so I never actually need to look up users by username :)

**Comment by dlmelendez** [comment]
Maybe you could set the username as the email address value since email addresses are unique?

**Comment by defrosted** [comment]
I was considering this, but I think it's more cumbersome and confusing. By the way, in the original implementation, FindByIdAsync should also accept a username, right? 
In my case, FindByIdAsync uses user.id, FindByEmailAsync uses email, and FindByUserNameAsync is not allowed. Maybe to achieve full consistency it would indeed be nice to implement another index for UserName and make it somehow configurable... I'll leave it for your consideration, but feel free to reject this pull request.

**Pull request closed without merging**
